// <auto-generated />
using System;
using ActiveBear.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ActiveBear.Migrations
{
    [DbContext(typeof(ActiveBearContext))]
    partial class ActiveBearContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("ActiveBear.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<Guid?>("CreateUserId");

                    b.Property<string>("KeyHash");

                    b.Property<string>("Status");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ActiveBear.Models.ChannelAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ChannelId");

                    b.Property<string>("UserEncryptedKey");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("ChannelAuths");
                });

            modelBuilder.Entity("ActiveBear.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Channel");

                    b.Property<string>("EncryptedContents");

                    b.Property<DateTime>("SendDate");

                    b.Property<Guid>("Sender");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ActiveBear.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ChannelId");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ActiveBear.Models.Channel", b =>
                {
                    b.HasOne("ActiveBear.Models.User", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");
                });

            modelBuilder.Entity("ActiveBear.Models.ChannelAuth", b =>
                {
                    b.HasOne("ActiveBear.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId");

                    b.HasOne("ActiveBear.Models.User", "User")
                        .WithMany("ChannelAuths")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ActiveBear.Models.User", b =>
                {
                    b.HasOne("ActiveBear.Models.Channel")
                        .WithMany("AuthorisedUsers")
                        .HasForeignKey("ChannelId");
                });
#pragma warning restore 612, 618
        }
    }
}
